M48
; DRILL file {KiCad (6.0.7)} date Wed Mar  1 01:05:32 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-01T01:05:32+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.487Y-3.837
X4.537Y-1.937
X6.537Y-2.537
X6.537Y-3.637
X7.487Y-1.937
X7.737Y-3.837
T0
M30
